name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Get-User
        run: |
          users=(
            "Codey" 
            "Amir" 
            "Ashan"
            "Ben"
            "Candice"
            "Manik"
            "Richard"
            "Tristan"          
          )

          users_count=${#names[@]}
          rnd_user=${users[$RANDOM % $users_count]}  

          echo $rnd_user

      - name: Create-Work-Item
        env:
          PAT_TOKEN: ${{ secrets.AZUREDEVOPSPAT }}
        run: |
          curl 
          -H "Authorization: Bearer $PAT_TOKEN" \
          "https://dev.azure.com/RedbackOperationsTEST/Readback%20Operations%20Cyber%20Security%20Team/_apis/wit/wiql/f8801112-4c3d-4a41-a843-ae9d9f4dadb0?api-version=7.1"
