name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      # - Set-Up

      # - name: Get-User
      #   run: |
      #     users=(
      #       "s222250824@deakin.edu.au",   # Codey
      #       "ben.stephens@deakin.edu.au", # Ben
      #       "smithcan@deakin.edu.au",     # Candice
      #       "s224019868@deakin.edu.au",   # Ashan
      #       "azandieh@deakin.edu.au",     # Amir
      #       "s222092193@deakin.edu.au",   # Manik
      #       "rwhellum@deakin.edu.au",     # Richard
      #       "tapperley@deakin.edu.au"     # Tristan
      #     )

      #     users_count=${#users[@]}
      #     echo $RANDOM % $users_count
      #     rnd_user=${users[$RANDOM % $users_count]}  

      #     echo $rnd_user

      - name: Create-Work-Item
        env:
          PAT_TOKEN: ${{ secrets.AZUREDEVOPSPAT }}
          ORG: "redbackoperations"
          PROJECT: "Cybersecurity"
          TYPE: "task"
        run: |
          curl POST \
          --header "Authorization: Bearer $PAT_TOKEN" \
          --header "Content-Type: application/json-patch+json" \
          --data '[ 
            {
              "op": "add",
              "path": "/fields/System.Title",
              "from": null,
              "value": "Test Task 2"
            },
            {
              "op": "add",
              "path": "/fields/System.AssignedTo",
              "from": null,
              "value": "s222250824@deakin.edu.au"
            }
          ]' \
          "https://dev.azure.com/${ORG}/${PROJECT}/_apis/wit/workitems/\$${TYPE}?suppressNotifications={true}&api-version=5.0"