name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      # - name: Get-User
      #   run: |
      #     users=(
      #       "Codey" 
      #       "Amir" 
      #       "Ashan"
      #       "Ben"
      #       "Candice"
      #       "Manik"
      #       "Richard"
      #       "Tristan"          
      #     )

      #     users_count=${#users[@]}
      #     echo $RANDOM % $users_count
      #     rnd_user=${users[$RANDOM % $users_count]}  

      #     echo $rnd_user

      - name: Create-Work-Item
        env:
          PAT_TOKEN: ${{ secrets.AZUREDEVOPSPAT }}
          ORG: "redbackoperations"
          PROJECT: "Cybersecurity"
          TYPE: "task"
        run: |
          curl --verbose -X POST \
          --header "Authorization: Bearer $PAT_TOKEN" \
          --header "Content-Type: application/json-patch+json" \
          --data '[ 
            {
              "op": "add",
              "path": "/fields/System.Title",
              "from": null,
              "value": "Test Task"
            }
          ]' \
          "https://dev.azure.com/{${ORG}}/{${PROJECT}}/_apis/wit/workitems/${TYPE}?api-version=5.0"