name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Get IP
        run: ip addr | grep "inet "

      - name: inline-py
        run: |
          echo "hi"
