name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Get-User
        run: |
          users=(
            "Codey" 
            "Amir" 
            "Ashan"
            "Ben"
            "Candice"
            "Manik"
            "Richard"
            "Tristan"          
          )

          users_count=${#users[@]}
          rnd_user=${users[$RANDOM % $users_count]}  

          echo $rnd_user

      - name: Create-Work-Item
        env:
          PAT_TOKEN: ${{ secrets.AZUREDEVOPSPAT }}
          QUERY_ID: "06e965be-0e9b-4023-9b46-be51fb59e1b4"
        run: |
          curl -v \
          -H "Authorization: Bearer $PAT_TOKEN" \
          "https://dev.azure.com/RedbackOperationsTEST/Readback%20Operations%20Cyber%20Security%20Team/_apis/wit/$QUERY_ID?api-version=7.1" \
