# --------------------------------------------------------
#   File:         PR_Review_Automation.yaml
#   Author:       Codey Funston [s222250824@deakin.edu.au]
# 
#   Description:  Creates Azure DevOps task for each PR
#                 in repo. Randomly assigns a team 
#                 member to review.
# --------------------------------------------------------

name: Pull Request Review Setup

# Runs on every PR in main branch.
# on:
#   pull_request:
#     types: [opened, reopened]
#     branches:
#      - main

on: [push]

jobs:
  POST-to-Azure-DevOps-API:
    runs-on: ubuntu-latest

    steps:
      - name: Get Random Team Member
        run: |
          users=(
            "s222250824@deakin.edu.au",   # Codey
            "ben.stephens@deakin.edu.au", # Ben
            "smithcan@deakin.edu.au",     # Candice
            "s224019868@deakin.edu.au",   # Ashan
            "azandieh@deakin.edu.au",     # Amir
            "s222092193@deakin.edu.au",   # Manik
            "rwhellum@deakin.edu.au",     # Richard
            "tapperley@deakin.edu.au"     # Tristan
          )

          users_count=${#users[@]}
          rnd_user=${users[$RANDOM % $users_count]} 
          echo "RND_USER=${rnd_user}" >> $GITHUB_ENV

      - name: Create Task

        env:
          PAT_TOKEN:  "${{ secrets.AZUREDEVOPSPAT }}"

          # URI Params
          ORG:        "redbackoperations"
          PROJECT:    "Cybersecurity"
          TEAM:       "SecDevOps"
          API_VER:    "api-version=7.1"
          NOTIF:      "suppressNotifications={true}"
          TYPE:       "task"
          USER:       "${RND_USER}"

          PR_TITLE:   "PR: ${{ github.event.pull_request.title }}"
        
        run: |
          curl -X POST \
          --header "Authorization: Bearer $PAT_TOKEN" \
          --header "Content-Type: application/json-patch+json" \
          --data '[ 
            {
              "op": "add",
              "path": "/fields/System.Title",
              "from": null,
              "value": "'"${RND_USER}"'"
            },
            {
              "op": "add",
              "path": "/fields/System.AssignedTo",
              "from": null,
              "value": "s222250824@deakin.edu.au"
            }
            ]' \
          "https://dev.azure.com/${ORG}/${PROJECT}/_apis/wit/workitems/\$${TYPE}?${NOTIF}&${API_VER}" \
          | jq