name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - automation-test

# Jobs to run
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: inline-py
        shell: bash
        run: |
          users=(
            "Codey" 
            "Amir" 
            "Ashan"
            "Ben"
            "Candice"
            "Manik"
            "Richard"
            "Tristan"          
          )

          users_count=${#names[@]}
          rnd_user=${users[$RANDOM % $users_count]}  

          echo $rnd_user
